### ISSUE TITLE
Missing headers when starting scan

### ISSUE THREAD

**Issue by awkwardcatfriend** [sleeyax/x-bot-sweeper#5]
Hello! I'd really love to use your extension, but when I click "Scan" on my followers page I can't seem to get around this error:

<img width="500" alt="Screenshot 2024-10-30 at 21 33 11" src="https://github.com/user-attachments/assets/003250ae-0ba6-4084-afce-6163780eb664">

I've tried to go to x.com/home to fix it, but it's not very clear what the next step would be to solve the issue? I've re-installed the extension but it did not help.
I'm using latest Chrome version 130.0

Thank you!

**Comment by sleeyax** [comment]
Thank you for trying out the extension! As soon as you finished loading the webpage at https://x.com/home you should be able to click 'Scan' successfully (the error message doesn't disappear by itself).

**Comment by awkwardcatfriend** [comment]
> Thank you for trying out the extension! As soon as you finished loading the webpage at https://x.com/home you should be able to click 'Scan' successfully (the error message doesn't disappear by itself).

I've been going back and forth to home, but the error is always there when I click Scan :(

**Comment by sleeyax** [comment]
Did a clean reinstall and I can't reproduce your issue. Are you logged in to x.com?

If so, can you go to `chrome://extensions/` and click on the  'Details' button:

![image](https://github.com/user-attachments/assets/c9b79ff2-4928-4dcc-a9c4-5cb78ef1af26)

Then make sure the following is checked (it should by default but maybe it got unchecked it for some reason):

![image](https://github.com/user-attachments/assets/2085b497-0edf-415d-b79a-4389b901e67c)

Finally, if that still doesn't work, do you have any other extensions installed for X (that could be interfering)?

**Comment by awkwardcatfriend** [comment]
> If so, can you go to `chrome://extensions/` and click on the 'Details' button:
> Then make sure the following is checked (it should by default but maybe it got unchecked it for some reason):

It's enabled :)

> Finally, if that still doesn't work, do you have any other extensions installed for X (that could be interfering)?

There shouldn't be... I just tried with another X profile and there the scanning works! But not on the profile where I'd need it :') The error changed now though? This video might not help at all, but, well:

https://github.com/user-attachments/assets/b95c4685-da2b-46ac-91ce-cee8dcca03d2

**Comment by sleeyax** [comment]
Hmm OK I suppose we need to debug this further then. Anything special I should know about the account / profile you're trying with?

R mouse click anywhere on the open extension window and click 'Inspect':

![image](https://github.com/user-attachments/assets/ccd45fc9-73a6-4046-828a-c20260de5af4)

Then 'console' and show me the output:

![image](https://github.com/user-attachments/assets/361ac888-3345-4c18-9bda-66d54f2c6d7c)

**Comment by sleeyax** [comment]
> The error changed now though? This video might not help at all, but, well:

Come to think of it, this is probably because the extension is incorrectly trying to fetch your current account's followers using the authentication headers from your other (working) account. You can 'reset' the extension data by first uninstalling and then reinstalling it.

For some reason the extension fails to fetch your authentication headers on your target account. It would still be helpful if you could show me if there are any errors as instructed in my comment above.

**Comment by awkwardcatfriend** [comment]
So, I removed the extension, logged out of my other account, installed it again and now we're back to this error:

<img width="1365" alt="Screenshot 2024-11-02 at 11 54 21" src="https://github.com/user-attachments/assets/7d4c5fd1-b1f9-40e8-a660-1df960a5c633">

**Comment by Stampede** [comment]
I had the exact same problem with Brave for Linux `Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)`.

I only have one X account in that browser. I logged out of X, then left the Bot Sweeper window open as I signed back in and it started working right away.

Thanks so much for publishing this script. I was getting really tired of manually click --> blocking so many bots!

**Comment by sleeyax** [comment]
@awkwardcatfriend can you try the solution/work-around above?

**Comment by awkwardcatfriend** [comment]
Oh my! It worked! Gosh, why didn't I think of "log out and back in again"... gee... 😂
Thanks for your time 🥲

**Comment by sleeyax** [comment]
Awesome! I'll update the FAQ in a moment and mention the work-around. I don't think there's an easy way for me to fix this otherwise, unless someone is willing to debug further and manage to find more information about this.
